name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 3 hours
    - cron: "0 */3 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "TRUE"
          SHOW_PROJECTS: "FALSE"
          SHOW_PROFILE_VIEWS: "FALSE"
          SHOW_TIMEZONE: "FALSE"
          SHOW_SHORT_INFO: "FALSE"
          SHOW_LOC_CHART: "FALSE"
          SHOW_LINES_OF_CODE: "TRUE"
          SHOW_LANGUAGE_PER_REPO: "TRUE"
        
