name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs Every 3rd Hour
    - cron: '0 */12 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          UPDATED_DATE_FORMAT: "%B %d, %Y"
          SHOW_OS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TIMEZONE: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          
        
