name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "TRUE"
          SHOW_PROJECTS: "FALSE"
          SHOW_PROFILE_VIEWS: "TRUE"
          SHOW_TIMEZONE: "TRUE"
          SHOW_SHORT_INFO: "TRUE"
          SHOW_LOC_CHART: "TRUE"
          SHOW_LINES_OF_CODE: "TRUE"
          SHOW_LANGUAGE_PER_REPO: "TRUE"
          COMMIT_BY_ME: "TRUE"
          SHOW_TOTAL_CODE_TIME: "TRUE"
          SHOW_COMMIT: "TRUE"
          SHOW_DAYS_OF_WEEK: "TRUE"
          SHOW_LANGUAGE: "TRUE"
          SHOW_EDITORS: "TRUE"
          
        
